#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Simple script to hash an input string using Radix-Hash.
"""
from model.radix_hash import process_block

def main():
    text =  """
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam quis cursus libero. Etiam non erat neque. Nulla massa nisl, consequat nec mauris ac, hendrerit aliquet augue. Vestibulum elementum volutpat justo, ut ornare nisi imperdiet a. Mauris fringilla, nisi blandit sagittis finibus, justo nulla efficitur elit, vitae fringilla dolor ex a lectus. Proin pulvinar sem tellus, ac varius ipsum egestas vitae. Praesent non nunc purus. Donec blandit mi et eros dignissim, fringilla commodo eros rhoncus. Suspendisse facilisis interdum mauris, in congue arcu scelerisque nec. Suspendisse eu dolor ullamcorper, feugiat ligula ut, dapibus neque. Cras nunc est, rutrum sit amet viverra maximus, laoreet vitae urna. Aliquam egestas turpis consequat tempor elementum.

Cras maximus, turpis eu bibendum ultrices, sem metus porta nunc, nec feugiat risus metus et lacus. Suspendisse sed leo ac ligula elementum elementum. Proin iaculis cursus mauris, non lacinia tellus vulputate sit amet. Proin ac euismod orci. Donec ut nunc commodo, imperdiet diam vel, lobortis ante. Mauris venenatis mollis libero sed pharetra. Vivamus lacus magna, laoreet vitae luctus sit amet, gravida mattis risus.

Maecenas hendrerit pellentesque eros, non feugiat lectus pellentesque vitae. Quisque facilisis maximus accumsan. Mauris eu ex rutrum, ornare sem eget, volutpat lorem. Duis blandit aliquam mi id semper. Sed ultricies, ligula ac condimentum commodo, orci libero fermentum velit, id tincidunt mauris sapien in justo. Maecenas condimentum laoreet magna a facilisis. Maecenas sodales lorem eu orci finibus porta. Proin euismod, augue vitae malesuada pulvinar, risus felis lacinia metus, ac pellentesque lorem felis eu dolor. Nam sodales lacus quis ante imperdiet, eu efficitur nunc malesuada.

Nulla ante magna, pretium nec mollis sed, cursus ut turpis. Maecenas rhoncus non diam vel lobortis. Sed ultrices vehicula porta. Vivamus eget luctus ligula. Integer vestibulum ante a ante malesuada tempor. Phasellus vel luctus ante, id finibus nisi. Nam purus orci, pulvinar eget risus et, commodo vehicula eros. Aenean ut libero aliquam, laoreet lectus sit amet, aliquam lacus. Pellentesque dignissim eleifend sem vitae lacinia. Fusce sit amet molestie mi. Cras eget neque magna. Maecenas eget justo at lorem laoreet varius placerat ut lorem. Duis et sem ac magna semper convallis ac eu lectus. Pellentesque non scelerisque nisl, vitae mollis orci. Vestibulum accumsan blandit purus sit amet venenatis.

Vestibulum vel aliquet purus. Duis eget posuere ex, nec feugiat sapien. Vivamus a felis in est bibendum euismod vitae vitae mi. Maecenas efficitur arcu eu neque luctus, vitae volutpat metus interdum. Aenean et quam nec mauris dictum ultrices. Vestibulum viverra eu magna vitae sodales. Suspendisse potenti. Pellentesque vestibulum nunc eget erat ornare tristique. Maecenas tincidunt nulla eu nunc dignissim tempor.

Sed et nulla iaculis, ornare erat nec, aliquet leo. Sed quis magna diam. Sed feugiat mi vitae nisi dapibus, at maximus eros aliquam. In bibendum interdum euismod. Aliquam erat volutpat. Nullam venenatis sed eros a varius. Fusce in ex cursus, tincidunt turpis in, viverra sapien. Vestibulum lobortis suscipit metus sit amet volutpat. Nullam at magna massa. Maecenas mi magna, sodales vel arcu vitae, auctor mattis leo. Maecenas aliquam erat at nunc iaculis, nec molestie mi porttitor. Donec vestibulum maximus ante ac volutpat. Nam a vulputate turpis. Maecenas convallis sed ligula a porttitor.

Mauris laoreet velit molestie, tincidunt elit sed, blandit magna. Ut consequat tincidunt elit. Praesent mattis enim non orci hendrerit, a cursus erat tristique. Curabitur quis urna interdum, bibendum felis sed, pulvinar risus. Quisque fermentum eros in consectetur viverra. Etiam gravida tincidunt est non lacinia. Vestibulum feugiat mi tempus erat gravida, non porta lorem pulvinar. Ut eros massa, ornare nec nisl a, ultrices porttitor nibh. Aenean sodales neque in convallis mollis. Cras at placerat odio. Phasellus vitae eleifend elit, id tincidunt urna.

Praesent sed tempus nisl. In dignissim nibh quis fermentum placerat. Pellentesque ac molestie nunc, convallis dignissim est. Phasellus sed tortor nibh. In faucibus dui nisi, vitae pellentesque arcu egestas vel. Donec et ipsum facilisis turpis maximus aliquet. Pellentesque bibendum ultricies mollis. Quisque facilisis scelerisque leo, vitae venenatis elit ullamcorper ut. Sed mollis, ligula at vestibulum pharetra, lorem mauris efficitur metus, nec elementum mauris nunc sit amet leo. Vivamus mollis lobortis rutrum. Curabitur neque lorem, pharetra sed bibendum sed, consectetur nec mauris. Sed malesuada lectus aliquam nibh auctor, at feugiat felis vehicula. Cras mattis efficitur sem, sed tristique purus molestie ac. Vestibulum vulputate justo enim, non auctor leo facilisis et.

Vestibulum consequat hendrerit tincidunt. Quisque interdum urna quis dolor posuere congue. Donec non nulla mauris. Duis auctor arcu id imperdiet venenatis. Nam ut consequat quam. Ut iaculis risus justo, ut bibendum neque porttitor nec. Integer consectetur eros non ex mattis elementum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus tempus urna sed semper. Suspendisse congue nulla in purus convallis pellentesque. Curabitur aliquam metus quis odio consectetur condimentum. Nullam dignissim nec libero in tincidunt. Aliquam massa mi, dapibus in dapibus et, aliquam non nisl. Aenean ut congue mauris, vitae dignissim libero.

Etiam facilisis porta magna, id interdum urna. Suspendisse id nisl pellentesque, finibus magna quis, ornare dolor. Nunc tincidunt nulla tellus. Etiam faucibus, lectus ac mattis bibendum, neque orci fermentum nunc, vitae tempor felis risus vitae urna. Praesent quam massa, luctus non accumsan ac, sagittis vitae orci. Morbi egestas hendrerit neque, posuere ornare eros facilisis vel. Duis quis malesuada tellus. Aliquam imperdiet tortor sed ex convallis faucibus. Curabitur rhoncus ante nec mauris ultricies accumsan. Nulla consectetur porta libero, id pretium arcu. Pellentesque varius nisi faucibus vulputate ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit efficitur neque eu condimentum. Suspendisse potenti.

Sed interdum viverra feugiat. Aenean accumsan neque at accumsan ultricies. Nulla facilisi. Aenean sed diam neque. Curabitur at sapien quis magna placerat tempor ac quis odio. Quisque et consectetur urna, at pulvinar ipsum. Proin et elit a tellus luctus egestas.

Duis molestie elit dui, tincidunt auctor ipsum aliquet id. In ornare lectus vel sollicitudin consectetur. Nam posuere egestas quam. In vitae purus diam. Sed faucibus nunc enim, sit amet molestie diam gravida sed. Aliquam rhoncus velit leo, id fringilla sapien fermentum vitae. Morbi eu eros ac massa tincidunt feugiat sit amet a turpis. Maecenas suscipit nibh quis arcu consequat euismod. Duis condimentum molestie libero vitae pellentesque. Phasellus nulla nunc, sodales non ipsum vel, vestibulum commodo augue. Etiam tristique facilisis rutrum. Etiam porttitor, arcu in malesuada consequat, mi velit accumsan erat, ut tristique mi quam quis nibh. Nunc lobortis ac justo ut viverra. Donec mollis ligula nec eleifend molestie.

Fusce facilisis aliquam nibh ut facilisis. Curabitur posuere tincidunt interdum. Nullam fringilla, mi et varius viverra, elit justo tristique eros, at rutrum tellus ante nec elit. Praesent ullamcorper velit tempus mauris tempor suscipit. In efficitur commodo tortor ac viverra. Ut hendrerit metus sit amet urna faucibus, a porttitor leo pharetra. In ultricies ultrices eros, vel hendrerit orci facilisis ac. Maecenas quis dui gravida, mattis dui at, posuere eros. Duis mollis, odio nec pulvinar vulputate, arcu eros luctus tellus, eu venenatis dolor nisi eget ipsum. Nullam lacinia vitae neque et dignissim. Etiam varius eros ac ex ullamcorper dignissim. Nullam nec tempus sem. Sed in fringilla dolor. In bibendum dolor sed ultricies volutpat.

Nunc ac risus mauris. Nam in justo aliquet, sagittis turpis ac, rhoncus lectus. Suspendisse fringilla nulla ut dolor hendrerit, et tempor purus tincidunt. Nam fermentum felis at dui congue tincidunt. Donec cursus nisi ac luctus fermentum. Nam eleifend eleifend nibh at ultricies. Aliquam erat volutpat. Proin varius tortor quis mauris vehicula, quis hendrerit nisl efficitur.

Proin eu quam massa. Pellentesque vel felis ut ex varius volutpat. Cras quis turpis nec purus hendrerit iaculis. Nulla facilisi. Suspendisse condimentum libero vel justo ultrices suscipit quis ut purus. Nulla vestibulum nulla quam, eget accumsan dolor tempor quis. Nulla eu velit vel diam finibus consectetur. Nunc euismod, lacus eget imperdiet maximus, neque eros blandit odio, quis volutpat nunc orci a lacus. Integer bibendum, neque at suscipit consequat, nulla massa pharetra eros, quis consectetur tortor turpis sit amet urna. Nulla interdum nec lectus at laoreet. Donec fermentum non ligula quis tincidunt.

Pellentesque commodo luctus urna, eget dictum dolor sagittis dignissim. Cras vel ornare turpis. Cras volutpat quam id metus luctus hendrerit. Curabitur egestas hendrerit quam, id tempus urna fringilla et. Etiam at mollis tellus. Cras pretium neque sit amet quam tempus vestibulum pulvinar ut sapien. Aenean urna odio, ullamcorper nec ipsum pharetra, congue fringilla quam. Morbi vestibulum ullamcorper ipsum. In porttitor molestie risus, ac interdum odio ornare quis.

Praesent non facilisis dolor. Nam dignissim venenatis mauris, nec congue odio hendrerit a. Mauris pulvinar, lorem at elementum tincidunt, felis arcu efficitur dui, vel pretium ligula tortor eu purus. Nam sagittis arcu ipsum, nec suscipit enim facilisis ac. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur sodales ex id libero tincidunt imperdiet. Morbi ornare quis dui quis eleifend. Sed facilisis et odio nec porta.

Suspendisse molestie volutpat augue, eu suscipit urna ornare sit amet. In egestas turpis ac ultricies bibendum. Mauris dignissim arcu eget odio interdum, ultrices varius lectus tempus. Cras rutrum, urna a elementum lacinia, elit tellus ultricies orci, ut bibendum lorem quam ac ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi bibendum libero et urna elementum, at mattis orci laoreet. Mauris condimentum eget neque nec faucibus.

In molestie ipsum sit amet luctus pharetra. Praesent sed odio sagittis, fermentum ligula ut, feugiat neque. Fusce laoreet ultrices arcu, et egestas mauris viverra ac. Morbi id nunc dictum, placerat dui a, tempus leo. Nulla convallis, sem id molestie elementum, neque ex tristique lectus, vel blandit orci enim ut massa. Vestibulum at fringilla purus. Vivamus pharetra nunc vitae quam pharetra, et ullamcorper nulla aliquet. Nulla quam augue, sodales a interdum a, vestibulum at libero. Fusce semper, nulla non porttitor tristique, nulla nibh rhoncus magna, eget auctor erat mi at sapien. Vestibulum ac mi at sapien lobortis fringilla in a mauris. Phasellus viverra elit massa, vitae tempor lacus lobortis vel. Integer vel metus eget dui imperdiet vestibulum vitae ut purus. Donec a tempus nisi. Sed vitae pretium dolor, ac posuere est.


    """
    hash_bits = process_block(text)
    print(f"\nInput text: {text}")
    print(f"772-bit hash: {hash_bits}")
    print(f"Hex hash: {hex(int(hash_bits,2))[2:]}")

if __name__ == "__main__":
    main()
